### ISSUE TITLE
Question: how to actually use?

### ISSUE THREAD

**Issue by nonunknown777** [DigitallyTailored/godot4-quadtree#1]
this is an awesome plugin, but how to the user configure the LOD? or the plugin uses the default generated lods? do we need to connect signals or something?

**Comment by DigitallyTailored** [comment]
Thank you!

That's a good point, I should probably add some instructions.. :smile: 

In the demo scene, if you click the node with the script attached:

![image](https://github.com/DigitallyTailored/godot4-quadtree/assets/13086157/d9a4a747-8c29-4d49-85a3-d6a6cf9be8a1)

Then in the inspector on the right you can edit the key values and you should see the quadtree update in the editor:

![image](https://github.com/DigitallyTailored/godot4-quadtree/assets/13086157/1646c214-3388-4380-b0b7-975f3b83b5bb)

If you want to change what is generated, for instance using a custom terrain material or perhaps have some logic for the high-depth chunks to load grass and small rocks, you'd want to edit this bit of the script:

![image](https://github.com/DigitallyTailored/godot4-quadtree/assets/13086157/c2056f50-b2da-452c-a4e7-fa56cde0d7a3)

Everything from line 79 to 85 actually adds the chunk.

**Comment by nonunknown777** [comment]
thanks for the answer I'll try here
